package markdown

// MarkdownRenderResult describes Markdown generated by MarkdownBuilder.
type MarkdownRenderResult struct {
	Text   string `json:"text"`
	Bytes  int    `json:"bytes"`
	Blocks int    `json:"blocks"`
}

type markdownDocument struct {
	Blocks []markdownBlock
}

type markdownBlock interface {
	markdownBlockKind() string
}

type headingBlock struct {
	Level int
	Text  []markdownInline
}

type paragraphBlock struct {
	Inlines []markdownInline
}

type rawBlock struct {
	Markdown string
}

type thematicBreakBlock struct{}

type blockquoteBlock struct {
	Lines []string
}

type calloutBlock struct {
	Kind  string
	Title string
	Lines []string
}

type listBlock struct {
	Ordered bool
	Start   int
	Items   []listItem
}

type checklistBlock struct {
	Items []checklistItem
}

type codeBlock struct {
	Language string
	Code     string
}

type tableBlock struct {
	Columns []tableColumn
	Rows    [][]markdownInline
}

type listItem struct {
	Inlines []markdownInline
}

type checklistItem struct {
	Checked bool
	Inlines []markdownInline
}

type tableColumn struct {
	Label []markdownInline
	Align TableAlignment
}

func (headingBlock) markdownBlockKind() string       { return "heading" }
func (paragraphBlock) markdownBlockKind() string     { return "paragraph" }
func (rawBlock) markdownBlockKind() string           { return "raw" }
func (thematicBreakBlock) markdownBlockKind() string { return "thematicBreak" }
func (blockquoteBlock) markdownBlockKind() string    { return "blockquote" }
func (calloutBlock) markdownBlockKind() string       { return "callout" }
func (listBlock) markdownBlockKind() string          { return "list" }
func (checklistBlock) markdownBlockKind() string     { return "checklist" }
func (codeBlock) markdownBlockKind() string          { return "codeBlock" }
func (tableBlock) markdownBlockKind() string         { return "table" }

type markdownInline interface {
	markdownInlineKind() string
}

type TextInline struct {
	Text string `json:"text"`
}

type RawInline struct {
	Markdown string `json:"markdown"`
}

type CodeInline struct {
	Code string `json:"code"`
}

type EmphasisInline struct {
	Children []markdownInline `json:"-"`
}

type StrongInline struct {
	Children []markdownInline `json:"-"`
}

type LinkInline struct {
	Text  []markdownInline `json:"-"`
	URL   string           `json:"url"`
	Title string           `json:"title,omitempty"`
}

func (TextInline) markdownInlineKind() string     { return "text" }
func (RawInline) markdownInlineKind() string      { return "raw" }
func (CodeInline) markdownInlineKind() string     { return "code" }
func (EmphasisInline) markdownInlineKind() string { return "emphasis" }
func (StrongInline) markdownInlineKind() string   { return "strong" }
func (LinkInline) markdownInlineKind() string     { return "link" }

type TableAlignment string

const (
	AlignDefault TableAlignment = "default"
	AlignLeft    TableAlignment = "left"
	AlignCenter  TableAlignment = "center"
	AlignRight   TableAlignment = "right"
)
