// Code generated by logcopter-gen; DO NOT EDIT.

package extract

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.goja-text.pkg.extract")
