// Code generated by xgoja; DO NOT EDIT.
package main

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"

	"github.com/go-go-golems/go-go-goja/pkg/xgoja/app"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/providerapi"
	go_go_goja_core "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/core"
	go_go_goja_host "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host"
	goja_text "github.com/go-go-golems/goja-text/pkg/xgoja/providers/text"
)

const embeddedSpecJSON = `{
  "name": "goja-text",
  "appName": "goja-text",
  "target": {
    "kind": "xgoja",
    "output": "dist/goja-text"
  },
  "packages": [
    {
      "id": "goja-text",
      "import": "github.com/go-go-golems/goja-text/pkg/xgoja/providers/text",
      "register": "Register",
      "replace": "../.."
    },
    {
      "id": "go-go-goja-core",
      "import": "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/core",
      "register": "Register"
    },
    {
      "id": "go-go-goja-host",
      "import": "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host",
      "register": "Register"
    }
  ],
  "runtimes": {
    "main": {
      "modules": [
        {
          "package": "goja-text",
          "name": "markdown",
          "as": "markdown"
        },
        {
          "package": "goja-text",
          "name": "sanitize",
          "as": "sanitize"
        },
        {
          "package": "goja-text",
          "name": "extract",
          "as": "extract"
        },
        {
          "package": "go-go-goja-core",
          "name": "path",
          "as": "path"
        },
        {
          "package": "go-go-goja-core",
          "name": "yaml",
          "as": "yaml"
        },
        {
          "package": "go-go-goja-host",
          "name": "fs",
          "as": "fs",
          "config": {
            "allow": true
          }
        }
      ]
    }
  },
  "commands": {
    "eval": {
      "enabled": true,
      "runtime": "main",
      "name": "eval"
    },
    "run": {
      "enabled": true,
      "runtime": "main",
      "name": "run"
    },
    "repl": {
      "enabled": true,
      "runtime": "main",
      "name": "repl"
    },
    "jsverbs": {
      "enabled": true,
      "runtime": "main",
      "name": "verbs",
      "mount": "root"
    }
  },
  "jsverbs": [
    {
      "id": "goja-text-bundled-verbs",
      "path": "xgoja_embed/jsverbs/goja_text_bundled_verbs",
      "embed": true
    }
  ],
  "help": {
    "sources": [
      {
        "id": "goja-text-runtime-api",
        "embed": false,
        "package": "goja-text",
        "source": "runtime-api"
      }
    ]
  }
}
`

//go:embed xgoja_embed/jsverbs/*
var embeddedJSVerbs embed.FS

func main() {
	registry := providerapi.NewRegistry()
	must(goja_text.Register(registry))
	must(go_go_goja_core.Register(registry))
	must(go_go_goja_host.Register(registry))
	root, err := app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON, EmbeddedJSVerbs: embeddedJSVerbs, EmbeddedHelp: nil, EmbeddedAssets: nil})
	must(err)
	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func decodeSpec() *app.Spec {
	spec := &app.Spec{}
	must(json.Unmarshal([]byte(embeddedSpecJSON), spec))
	return spec
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
