// Code generated by xgoja; DO NOT EDIT.
package main

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"

	"github.com/go-go-golems/go-go-goja/pkg/xgoja/app"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/providerapi"
	go_go_goja_core "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/core"
	go_go_goja_host "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host"
	goja_text "github.com/go-go-golems/goja-text/pkg/xgoja/providers/text"
)

const embeddedSpecJSON = `{
  "name": "goja-text",
  "appName": "goja-text",
  "target": {
    "kind": "xgoja",
    "output": "dist/goja-text"
  },
  "packages": [
    {
      "id": "goja-text",
      "import": "github.com/go-go-golems/goja-text/pkg/xgoja/providers/text",
      "register": "Register",
      "replace": "../.."
    },
    {
      "id": "go-go-goja-core",
      "import": "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/core",
      "register": "Register"
    },
    {
      "id": "go-go-goja-host",
      "import": "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host",
      "register": "Register"
    }
  ],
  "modules": [
    {
      "package": "goja-text",
      "name": "markdown",
      "as": "markdown"
    },
    {
      "package": "goja-text",
      "name": "sanitize",
      "as": "sanitize"
    },
    {
      "package": "goja-text",
      "name": "extract",
      "as": "extract"
    },
    {
      "package": "goja-text",
      "name": "template",
      "as": "template"
    },
    {
      "package": "go-go-goja-core",
      "name": "path",
      "as": "path"
    },
    {
      "package": "go-go-goja-core",
      "name": "yaml",
      "as": "yaml"
    },
    {
      "package": "go-go-goja-host",
      "name": "fs",
      "as": "fs",
      "config": {
        "allow": true
      }
    },
    {
      "package": "go-go-goja-host",
      "name": "fs",
      "as": "fs:assets",
      "config": {
        "embedded": {
          "allow": true,
          "mounts": [
            {
              "asset": "goja-text-template-assets",
              "mount": "/templates"
            }
          ]
        }
      }
    }
  ],
  "commands": {
    "eval": {
      "enabled": true,
      "name": "eval"
    },
    "run": {
      "enabled": true,
      "name": "run"
    },
    "repl": {
      "enabled": true,
      "name": "repl"
    },
    "jsverbs": {
      "enabled": true,
      "name": "verbs",
      "mount": "root"
    }
  },
  "jsverbs": [
    {
      "id": "goja-text-bundled-verbs",
      "path": "xgoja_embed/jsverbs/goja_text_bundled_verbs",
      "embed": true
    }
  ],
  "help": {
    "sources": [
      {
        "id": "goja-text-runtime-api",
        "embed": false,
        "package": "goja-text",
        "source": "runtime-api"
      }
    ]
  },
  "assets": [
    {
      "id": "goja-text-template-assets",
      "path": "xgoja_embed/assets/goja_text_template_assets",
      "embed": true
    }
  ]
}
`

//go:embed xgoja_embed/jsverbs/*
var embeddedJSVerbs embed.FS

//go:embed all:xgoja_embed/assets/*
var embeddedAssets embed.FS

func main() {
	registry := providerapi.NewProviderRegistry()
	must(goja_text.Register(registry))
	must(go_go_goja_core.Register(registry))
	must(go_go_goja_host.Register(registry))
	root, err := app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON, EmbeddedJSVerbs: embeddedJSVerbs, EmbeddedHelp: nil, EmbeddedAssets: embeddedAssets})
	must(err)
	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func decodeSpec() *app.RuntimeSpec {
	buildSpec := &app.RuntimeSpec{}
	must(json.Unmarshal([]byte(embeddedSpecJSON), buildSpec))
	return buildSpec
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
